"""Below-OP EPS risk band: robust (MAD) half-width + point-estimate isolation.

PLAN_tax_finance_overlay.md §3.1: the below-OP block (net financial / FX / one-offs)
swings -1,516 .. +3,407 KRW bn over the 8Q backtest. Folding that into the EPS point
estimate would overfit a tiny, outlier-heavy sample, so its volatility is expressed
as a SEPARATE band whose half-width is a robust scale of the realized block
contribution (block_term / NI). MAD is used so the 2025Q3 outlier cannot blow up the
width; a trimmed-std alternative is computed for the user comparison.

The band is applied as eps_point ± |eps_point| × half_width_pct and must leave the
point estimate itself untouched (bit-identical EPS).

Deterministic: block_contrib seeded from tests/fixtures/sk_hynix_block_contrib.json
(generated by scripts/diagnose_tax_finance.py over cached DART). No network.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import pytest

from engine.risk_band import build_eps_risk_band, robust_half_width
from schemas.models import EpsRiskBand, Overlay

FIXTURES = Path(__file__).parent / "fixtures"


def _block_contrib() -> list[float]:
    data = json.load(open(FIXTURES / "sk_hynix_block_contrib.json", encoding="utf-8"))
    return [q["block_contrib"] for q in data["quarters"]]


# --- Robust half-width (calibration math) ---------------------------------- #

def test_mad_half_width_matches_formula() -> None:
    """half_width = 1.4826 × MAD(block_contrib) × k, exactly."""
    bc = _block_contrib()
    # k = 1.0: 1.4826 × MAD = ~0.1519 (one robust sigma of the 8Q block swing).
    hw1 = robust_half_width(bc, k=1.0, method="mad")
    assert hw1 == pytest.approx(0.1519, abs=1e-3)
    # k scales linearly; the YAML draft uses k = 1.5.
    hw15 = robust_half_width(bc, k=1.5, method="mad")
    assert hw15 == pytest.approx(0.2279, abs=1e-3)
    assert hw15 == pytest.approx(hw1 * 1.5, rel=1e-9)


def test_trimmed_alternative_is_tighter_than_mad() -> None:
    """Trimmed-std (drop min & max) is the user-comparison alternative.

    Dropping the 2025Q3 (+) and 2025Q1 (-) extremes yields a tighter scale than
    full-sample 1.4826×MAD — surfaced so the user can choose method/k on sign-off.
    """
    bc = _block_contrib()
    mad = robust_half_width(bc, k=1.0, method="mad")
    trimmed = robust_half_width(bc, k=1.0, method="trimmed")
    assert trimmed == pytest.approx(0.1128, abs=1e-3)
    assert trimmed < mad


def test_draft_band_covers_at_least_six_of_eight_quarters() -> None:
    """At the draft k=1.5, the symmetric band around the point estimate covers
    >= 6/8 realized block swings (PLAN §4-3 draft acceptance)."""
    bc = _block_contrib()
    half_width = robust_half_width(bc, k=1.5, method="mad")
    covered = sum(1 for v in bc if abs(v) <= half_width)
    assert covered >= 6


def test_robust_half_width_rejects_empty_and_unknown_method() -> None:
    with pytest.raises(ValueError):
        robust_half_width([], k=1.0, method="mad")
    with pytest.raises(ValueError):
        robust_half_width([0.1, 0.2], k=1.0, method="nonsense")


# --- Band application leaves the point estimate untouched ------------------- #

def test_band_preserves_eps_point_bit_identical() -> None:
    """build_eps_risk_band echoes each EPS point exactly and brackets it ±width."""
    eps_points = [("2026Q1", 1500.0), ("2026Q2", 1600.0), ("2026Q3", 1700.0), ("2026Q4", 1800.0)]
    band = build_eps_risk_band(
        eps_points, half_width_pct=0.2279, method="mad", k=1.5
    )
    assert isinstance(band, EpsRiskBand)
    assert band.method == "mad" and band.k == 1.5
    assert band.half_width_pct == 0.2279
    for (label, eps), q in zip(eps_points, band.quarters):
        assert q.period_label == label
        assert q.eps_point == eps  # bit-identical, never recomputed
        assert q.eps_lower == pytest.approx(eps * (1 - 0.2279))
        assert q.eps_upper == pytest.approx(eps * (1 + 0.2279))


def test_band_carries_overlays_as_annotations_only() -> None:
    """Overlays ride along as annotations; they do not move the EPS point/band."""
    eps_points = [("2026Q2", 1600.0)]
    overlay = Overlay(
        as_of_date=date(2026, 5, 15),
        target_period_label="2026Q2",
        driver="USD/KRW FX valuation loss",
        direction="risk_down",
        magnitude=0.03,
        confidence=0.4,
    )
    band = build_eps_risk_band(
        eps_points, half_width_pct=0.2279, method="mad", k=1.5, overlays=[overlay]
    )
    assert band.overlays == [overlay]
    # Point + band identical to the no-overlay case (overlays are not consumed).
    assert band.quarters[0].eps_point == 1600.0
    assert band.quarters[0].eps_upper == pytest.approx(1600.0 * 1.2279)
    # The consumption seam is documented, not implemented.
    assert "valuation_bridge" in band.seam_note


def test_band_handles_negative_eps_symmetrically() -> None:
    """A loss quarter widens by magnitude, keeping lower < point < upper."""
    band = build_eps_risk_band(
        [("2026Q1", -200.0)], half_width_pct=0.2279, method="mad", k=1.5
    )
    q = band.quarters[0]
    assert q.eps_lower < q.eps_point < q.eps_upper
